# Just for demo purposes, keep the default to 1m
global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - 'rules/test.yml'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['localhost:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
