# Just for demo purposes, keep the default to 1m
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      # Which tests should be run? Defined in blackbox.yml
      module: [http_2xx]
    static_configs:
      - targets:
        # List of target domains for tests
        - http://prometheus.io
    relabel_configs:
      # Switching of some internal labels (out of scope for this demo)
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
